#!/usr/bin/env python3
"""Regenerate ntfy/Utils/OpenSourceLicenses.swift from the real license files.

usage: scripts/generate-oss-licenses.py <spm-checkouts-dir>

<spm-checkouts-dir> is the SwiftPM `checkouts` folder that holds the resolved
packages (firebase-ios-sdk, GoogleUtilities, GoogleDataTransport, promises,
nanopb). Run it after any change to Package.resolved, then check the component
list below still matches what the app links (see notes in the PR that added it).
The texts are copied verbatim; only the component metadata lives here.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "ntfy/Utils/OpenSourceLicenses.swift"


def main() -> None:
    checkouts = pathlib.Path(sys.argv[1])
    resolved = json.loads((ROOT / "ntfy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved").read_text())
    versions = {p["identity"]: p["state"]["version"] for p in resolved["pins"]}

    def read(rel: str) -> str:
        return (checkouts / rel).read_text().strip("\n")

    apache = read("firebase-ios-sdk/LICENSE")
    # The three Apache LICENSE files are byte-identical; GoogleUtilities' adds an MIT section after it.
    for rel in ("GoogleDataTransport/LICENSE", "promises/LICENSE"):
        assert read(rel) == apache, rel
    gu = read("GoogleUtilities/LICENSE")
    assert gu.startswith(apache), "GoogleUtilities LICENSE no longer starts with Apache-2.0"
    fuller = gu[len(apache):].split("=" * 80, 1)[1].strip("\n")
    fuller = fuller[: fuller.index("Comment from")].strip("\n")  # keep the notice, drop the trailing explanation
    assert "Landon J. Fuller" in fuller and "Permission is hereby granted" in fuller

    def apache_notice(copyright: str) -> str:
        return f"{copyright}\n\nLicensed under the Apache License, Version 2.0 (the \"License\"); the full text follows."

    components = [
        ("ntfy for iOS", "The app's source code, forked from binwiederhier/ntfy-ios", "MIT License",
         (ROOT / "LICENSE").read_text().strip("\n"), False),
        ("Firebase", f"firebase-ios-sdk {versions['firebase-ios-sdk']}: FirebaseCore, FirebaseCoreInternal, "
         "FirebaseCoreDiagnostics, FirebaseInstallations, FirebaseMessaging", "Apache License 2.0",
         apache_notice("Copyright 2017-2021 Google LLC"), True),
        ("GoogleUtilities", f"GoogleUtilities {versions['googleutilities']}", "Apache License 2.0",
         apache_notice("Copyright 2017-2021 Google LLC"), True),
        ("GoogleUtilities: isAppEncrypted", f"GoogleUtilities {versions['googleutilities']}, "
         "Environment/third_party/GULAppEnvironmentUtil.m", "MIT License", fuller, False),
        ("GoogleDataTransport", f"GoogleDataTransport {versions['googledatatransport']}", "Apache License 2.0",
         apache_notice("Copyright 2018-2020 Google LLC"), True),
        ("Promises", f"Promises (FBLPromises) {versions['promises']}", "Apache License 2.0",
         apache_notice("Copyright 2018 Google Inc. All rights reserved."), True),
        ("nanopb", f"nanopb {versions['nanopb']}", "zlib License", read("nanopb/LICENSE.txt"), False),
    ]

    def raw(text: str) -> str:
        assert '"""#' not in text
        return '#"""\n' + text + '\n"""#'

    lines = [
        "// GENERATED by scripts/generate-oss-licenses.py from the license files of the linked",
        "// packages and this repo's LICENSE. Do not edit by hand; rerun the script instead.",
        "",
        "import Foundation",
        "",
        "extension OpenSourceLicenses {",
        "    static let apache2Text = " + raw(apache),
        "",
        "    static let components: [OpenSourceComponent] = [",
    ]
    for name, detail, license, notice, shares_apache in components:
        lines += [
            "        OpenSourceComponent(",
            f"            name: {json.dumps(name)},",
            f"            detail: {json.dumps(detail)},",
            f"            licenseName: {json.dumps(license)},",
            "            notice: " + raw(notice) + ",",
            f"            licenseText: {'apache2Text' if shares_apache else 'nil'}",
            "        ),",
        ]
    lines += ["    ]", "}", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(components)} components)")


if __name__ == "__main__":
    main()
